//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightInfo()
        {
            this.PurchaseHistory = new HashSet<PurchaseHistory>();
        }
    
        public string Id { get; set; }
        public int CityIdFrom { get; set; }
        public int CityIdWhere { get; set; }
        public System.DateTime DateFrom { get; set; }
        public string NumberOfSeats { get; set; }
        public decimal Price { get; set; }
        public int IdAirline { get; set; }
        public System.DateTime DateWhere { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseHistory> PurchaseHistory { get; set; }
    }
}
