//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHistory
    {
        public int Id { get; set; }
        public string IdFlightInfo { get; set; }
        public int IdUser { get; set; }
        public int TIcketsCount { get; set; }
    
        public virtual FlightInfo FlightInfo { get; set; }
        public virtual Users Users { get; set; }
    }
}
